// Optional developer check: requires Playwright and an installed Chrome browser.
const { chromium } = require('playwright');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const os = require('node:os');
const path = require('node:path');
(async () => {
  const output = fs.mkdtempSync(path.join(os.tmpdir(), 'iron-horizon-check-'));
  const browser = await chromium.launch({ channel: 'chrome', headless: true, args: ['--enable-unsafe-swiftshader'] });
  try {
    const page = await browser.newPage({ viewport: { width: 1440, height: 900 } });
    const errors = [];
    page.on('pageerror', error => { errors.push(error.message); console.error('PAGE ERROR:', error.message); });
    page.on('response', response => { if (response.status() >= 400 && !response.url().endsWith('favicon.ico')) errors.push(`${response.status()} ${response.url()}`); });
    await page.goto('http://127.0.0.1:4177/iron-horizon/');
    await page.waitForFunction(() => !!window.ironHorizon);
    console.log('Initial state:', await page.evaluate(() => window.ironHorizon.getState()));
    await page.screenshot({ path: path.join(output, 'menu.png') });
    assert.equal(await page.locator('#startButton').isEnabled(), true);
    await page.locator('#trainingButton').click();
    await page.waitForFunction(() => window.ironHorizon.getState().mode === 'playing');
    assert.equal((await page.evaluate(() => window.ironHorizon.getState())).pointerLocked, true, 'Playing must require actual browser pointer lock');
    assert.equal(await page.locator('#world').evaluate(el => getComputedStyle(el).cursor), 'none');
    // Raise the sight onto the first target; the actual turret must follow.
    await page.locator('#world').dispatchEvent('mousemove', { movementX: 0, movementY: -45 });
    await page.waitForTimeout(1200);
    await page.locator('#world').dispatchEvent('mousedown', { button: 0 });
    await page.waitForFunction(() => window.ironHorizon.getState().hitCount === 1);
    const firstShot = await page.evaluate(() => window.ironHorizon.getState());
    assert.ok(firstShot.reload > 0, 'Gun should reload after firing');
    assert.equal(firstShot.hitCount, 1, 'The first aimed projectile should hit its target');
    await page.locator('#world').dispatchEvent('mousedown', { button: 0 });
    assert.equal((await page.evaluate(() => window.ironHorizon.getState())).shells, 0, 'Firing during reload must be blocked');
    await page.keyboard.down('KeyW'); await page.waitForFunction(() => window.ironHorizon.getState().position.z < 63); await page.keyboard.up('KeyW');
    let state = await page.evaluate(() => window.ironHorizon.getState());
    assert.ok(state.position.z < 63, 'W should move the tank forward');
    await page.keyboard.down('Space'); await page.waitForFunction(() => Math.abs(window.ironHorizon.getState().speed) < .3); await page.keyboard.up('Space');
    assert.ok(Math.abs((await page.evaluate(() => window.ironHorizon.getState())).speed) < .4, 'Brake should stop the tank');
    await page.keyboard.down('KeyA'); await page.waitForFunction(() => window.ironHorizon.getState().hullYaw > .35); await page.keyboard.up('KeyA');
    state = await page.evaluate(() => window.ironHorizon.getState());
    assert.ok(state.hullYaw > .3, 'A should turn the hull');
    assert.ok(Math.abs(state.turretYaw - state.hullYaw) > .2, 'Turret should remain independent from hull');
    await page.screenshot({ path: path.join(output, 'driving.png') });
    await page.evaluate(() => document.exitPointerLock());
    await page.waitForFunction(() => window.ironHorizon.getState().mode === 'paused');
    assert.equal((await page.evaluate(() => window.ironHorizon.getState())).pointerLocked, false);
    const paused = await page.evaluate(() => window.ironHorizon.getState());
    await page.waitForTimeout(350);
    assert.deepEqual((await page.evaluate(() => window.ironHorizon.getState())).position, paused.position, 'Pause must freeze simulation');
    await page.locator('#sound').uncheck();
    await page.locator('#resetButton').click();
    await page.waitForFunction(() => window.ironHorizon.getState().mode === 'playing');
    state = await page.evaluate(() => window.ironHorizon.getState());
    assert.equal(state.hitCount, 0); assert.equal(state.position.z, 65); assert.equal(state.reload, 0);
    // A stationary target is a solid obstacle: continuous forward driving cannot pass through it.
    await page.keyboard.down('KeyW'); await page.waitForFunction(() => { const s = window.ironHorizon.getState(); return s.position.z < 11 && s.speed === 0; }, null, { timeout: 20000 }); await page.keyboard.up('KeyW');
    state = await page.evaluate(() => window.ironHorizon.getState());
    assert.ok(state.position.z >= 8.5 && state.position.z < 11, `Expected collision in front of target, got z=${state.position.z}`);
    await page.reload(); await page.waitForFunction(() => !!window.ironHorizon);
    assert.equal(await page.locator('#sound').isChecked(), false, 'Sound setting must persist');
    await page.setViewportSize({ width: 960, height: 640 });
    await page.screenshot({ path: path.join(output, 'compact.png') });
    assert.equal(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth), false);
    await page.setViewportSize({ width: 1440, height: 900 });
    await page.locator('#startButton').click();
    await page.waitForFunction(() => window.ironHorizon.getState().mode === 'playing');
    assert.equal((await page.evaluate(() => window.ironHorizon.getState())).gameType, 'battle');
    await page.waitForFunction(() => window.ironHorizon.getState().match.time < 394, null, { timeout: 60000 });
    const battle = await page.evaluate(() => window.ironHorizon.getState());
    console.log('Battle state:', JSON.stringify(battle));
    assert.ok(battle.match.time < 402, 'Match timer should run');
    assert.ok(battle.targets.some(t => Math.abs(t.z) < 35), 'Bots must navigate into battle');
    assert.ok(battle.targets.some(t => t.hp < 100) || battle.stats.deaths > 0 || battle.hp < 100 || battle.match.tickets.blue < 100 || battle.match.tickets.red < 100, 'Bots should engage and deal damage');
    await page.screenshot({ path: path.join(output, 'battle.png') });
    await page.evaluate(() => document.exitPointerLock());
    await page.waitForFunction(() => window.ironHorizon.getState().mode === 'paused');
    const timer = (await page.evaluate(() => window.ironHorizon.getState())).match.time;
    await page.waitForTimeout(300);
    assert.equal((await page.evaluate(() => window.ironHorizon.getState())).match.time, timer, 'Pause must freeze bots and match time');
    // Emulate a preview/browser that explicitly refuses Pointer Lock.
    await page.reload(); await page.waitForFunction(() => !!window.ironHorizon);
    await page.evaluate(() => { document.getElementById('world').requestPointerLock = () => Promise.reject(new Error('blocked by host')); });
    await page.locator('#startButton').click();
    await page.waitForFunction(() => window.ironHorizon.getState().mode === 'playing');
    const denied = await page.evaluate(() => window.ironHorizon.getState());
    assert.equal(denied.pointerLocked, false);
    assert.equal(await page.locator('#pause').isVisible(), false);
    assert.equal(await page.locator('#world').evaluate(el => getComputedStyle(el).cursor), 'none');
    await page.keyboard.press('Escape');
    assert.equal(await page.locator('#externalBrowser').isVisible(), true);
    await page.locator('#resumeButton').click();
    await page.waitForFunction(() => window.ironHorizon.getState().mode === 'playing');
    await page.goto('http://127.0.0.1:4177/');
    assert.equal(await page.locator('a.spiel[href="iron-horizon/"]').count(), 1);
    assert.deepEqual(errors, [], 'No uncaught browser errors or missing assets');
    console.log(JSON.stringify({ status: 'PASS', checks: ['rendering', 'real pointer lock', 'hidden cursor', 'lock denial allows preview play', 'target hit', 'reload gate', 'movement', 'braking', 'independent turret', 'pause', 'reset', 'solid collision', 'settings persistence', 'compact layout', 'bot navigation', 'bot combat', 'match pause', 'collection link', 'browser errors'], screenshots: output }, null, 2));
  } finally { await browser.close(); }
})().catch(error => { console.error(error); process.exitCode = 1; });
